openapi: 3.0.0
info:
  title: School Timetable API
  description: API for managing school timetables, users, and classes.
  version: 1.0.0
paths:
  /login:
    post:
      tags:
        - login
      summary: Login and get a token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "john.doe@example.com"
                password:
                  type: string
                  example: "yourpasswordhash"
                  description: yourpassword hashed with SHA256
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "your.jwt.token.here"
                  user:
                    $ref: 'main.yaml#/components/schemas/User'
        '401':
          description: Unauthorized - wrong credentials
  /logout:
    post:
      tags:
        - login
      summary: Logout and invalidate token
      security:
      - BearerAuth: []
      responses:
        '200':
          description: Logout successful
        '401':
          description: Unauthorized - not logged in
  /currentUser:
    get:
      tags:
        - login
      summary: Returns currently logged in user.
      security:
      - BearerAuth: []
      responses:
        '200':
          description: Information about currently logged in user.
          content:
            application/json:
              schema:
                $ref: 'main.yaml#/components/schemas/User'
        '401':
          description: Unauthorized - not logged in
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT