openapi: 3.0.0
info:
  title: School Timetable API
  description: API for managing school timetables, users, and classes.
  version: 1.0.0
paths:
  /cafeteria:
    get: 
      summary: Get Menue in a defined time frame.
      tags:
        - cafeteria
      parameters:
        - name: date
          in: query
          required: false
          schema:
            type: string
            format: date
        - name: duration
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 7
            default: 1
            description: The amount of days the response should include.
      responses:
        '200':
          description: The Menue
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Menue'
        '401':
          description: Unauthorized
        '204':
          description: No Menue in this time frame.
          content:
            application/json:
              schema:
                type: object
                example: "[]"
components:
  schemas:
    Menue:
      type: object
      properties:
        date:
          type: string
          format: date
        cookteam:
          type: string
        mainDish:
          type: string
        mainDishVeg:
          type: string
        garnish:
          type: string
        dessert:
          type: string


