openapi: 3.0.0
info:
  title: School Timetable API
  description: API for managing school timetables, users, and classes.
  version: 1.0.0
components:
  schemas:
    Class:
      type: object
      properties:
        id:
          type: integer
          example: "101"
          readOnly: true
        name:
          type: string
          example: "5a"
        mainTeacherId:
          type: integer
          example: 1
        secondaryTeacherId:
          type: integer
          example: 1
    Lesson:
      type: object
      properties:
        id:
          type: string
          example: "101"
          readOnly: true
        subjects:
          type: array
          items:
            type: integer
            example: 1
            description: SubjectID
        teachers:
          type: array
          items:
            type: integer
            example: 1
            description: TeacherID
        classes:
          type: array
          items:
            type: integer
            example: 1
        startTime:
          type: string
          example: "2017-07-21T17:32:28Z"
          format: date-time
        endTime:
          type: string
          example: "2017-07-21T17:32:28Z"
          format: date-time
        rooms:
          type: array
          items:
            type: integer
            example: 1
    Subject:
      type: object
      properties:
        id:
          type: integer
          example: 101
          readOnly: true
        name:
          type: string
          example: "Mathematics"
    Teacher:
      type: object
      properties:
        id:
          type: integer
          example: 101
          readOnly: true
        userId:
          type: integer
        name:
          type: string
          example: "Mustermann"
        firstName:
          type: string
          example: "Max"
    Room:
      type: object
      properties:
        id:
          type: integer
          example: 101
          readOnly: true
        name:
          type: string
          example: "110"
        additionalInformation:
          type: string
          example: "Computerraum"
    
